services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - app-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  order-api:
    build: ./services/order-api
    image: order-api:dev
    ports:
      - "8000:8000"
    environment:
      - SERVICE_NAME=order-api
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - QUEUE_NAME=orders
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-net

  inventory-worker:
    build: ./services/inventory-worker
    image: inventory-worker:dev
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - QUEUE_NAME=orders
      - ORDER_API_URL=http://order-api:8000
    depends_on:
      redis:
        condition: service_healthy
      order-api:
        condition: service_started
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
